my:
  greeting: Hello from configuration file!
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:PUBLIC;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: root
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  aop:
    proxy-target-class: false
logging:
  config: src/main/resources/log4j2-spring.xml
  level.root: info
server:
  error:
    include-stacktrace: always
    include-message: always
jwt:
  secret: secret
  expiration: 600000
  header: Authorization
