spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:PUBLIC;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: '{cipher}63a0f9c24316ca4c095ce52924971926250afc251f7b444ff4036f6f05cf9896'
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
logging:
  config: src/main/resources/log4j2-spring.xml
  level.root: info